---

- hosts: "workers"
  remote_user: devops
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: ingress- execute script
      shell: |
        chmod +x worker.sh
        ./worker.sh
